services:
  comments-downloader:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - VIDEO_URL=https://www.youtube.com/watch?v=3TMWNkgbJL0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=comments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      # Gemini API ключи для мультиключевой системы
      - GEMINI_API_KEY=AIzaSyAQGZvaL4fACOmAWQKf-KEbpD_rytMxhos
      - GEMINI_API_KEY_1=AIzaSyAQGZvaL4fACOmAWQKf-KEbpD_rytMxhos # for project Generative Language Client
      - GEMINI_API_KEY_2=AIzaSyDLg48EwjCdgajNmqCXK4HLKAjtBcUXAns # for project My Project 94707
      - GEMINI_API_KEY_3=AIzaSyC3e8mHFb9wAPMQZAi184O6tC9VNkkbgWg # for project My Project 61890
    volumes:
      - ./:/app
    networks:
      - app-net

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

volumes:
  postgres-data:

networks:
  app-net:
    driver: bridge